config/routes.rb
Rails.application.routes.draw do
  root "movies#search"
  get "/results" => "movies#results"
  get "/search" => "movies#search"
  get "/movies/:id" => "movies#show", as: "details"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def search
		# Just renders the search form
	end

  def results
    data = RestClient.get 'http://www.omdbapi.com', {:params => {:s => params[:search]}}
    @results = JSON.parse(data.body)["Search"]
  end

  def show
    data = RestClient.get 'http://www.omdbapi.com', {:params => {:i => params[:id]}}
    @movie = JSON.parse(data.body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmdbSearchApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/results.html.erb
<h1>Results</h1>

<%@results.each do |movie| %>
  <li><%= movie["Title"] %> <%= link_to "Details", details_path(movie["imdbID"])%></li>
<%end %>

<%= link_to "Search Again", search_path %>

app/views/movies/search.html.erb
<h1>Movie Search</h1>

<%= form_tag('/results', {:method => :get}) do %>
  <%= text_field_tag :search %>
  <%= submit_tag %>
<% end %>



<!-- THE UNORGANIZED, MESSY IN-CLASS NOTES: -->
<!-- params.require(:movie).permit(:search)

params = 
	{
		action: "asdas"
		controller: "asd"
		search: "Charlie"
		momo: "awesome"
	}

name="movie[search]"

params[:momo] -->

app/views/movies/show.html.erb
<h1><%=@movie["Title"]%></h1>

<!-- <img src="<%#=@movie['Poster']%>"> -->
<%=image_tag @movie["Poster"]%>

<!-- <a href=""></a> -->
<%#=link_to  %>

<%@movie.each do |key,value| %>
  <li><%=key%>: <%=value%> </li>
<%end %>

<%= link_to "Search Again", search_path %>